SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES = butterfly_unit_no_imag.v

TOPLEVEL = butterfly_unit_no_imag
MODULE = test_butterfly_unit_no_imag

include $(shell cocotb-config --makefiles)/Makefile.sim
